#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}


# branches to build
branches:
  only:
    - master


#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: 
  - Visual Studio 2017

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input
  - choco install hugo

# clone directory
clone_folder: C:\projects\LearnToCode



# this is how to allow failing jobs in the matrix
matrix:
  fast_finish: true
  
environment:
  access_token:
    secure: 44rXJx5ePiHhRQh9LVZDrUXXFNxdydxEhThZiJp4sTP8O/EqN/8s+vWbWT7RyR6i


#---------------------------------#
#       build configuration       #
#---------------------------------#

# to add several platforms to build matrix:
platform:
  - x64

# to add several configurations to build matrix:
configuration:
  - Debug
  
install:
  - git submodule update --init --recursive

# We don't want MSBuild
build: off

# Use custom script to build
build_script:
- cmd: |-
    cd /d C:\projects\LearnToCode
    hugo
    

#---------------------------------#
#             deploy              #
#---------------------------------#

on_success:
  # Add private key to 
  - ps: $fileContent = "-----BEGIN RSA PRIVATE KEY-----`n"
  - ps: $fileContent += $env:priv_key.Replace(' ', "`n")
  - ps: $fileContent += "`n-----END RSA PRIVATE KEY-----`n"
  - ps: Set-Content $env:userprofile\.ssh\id_rsa $fileContent
  - mkdir C:\projects\deploy
  - cd C:\projects\deploy
  - git config --global user.email "kardospeter1994@hotmail.com"
  - git config --global user.name "Peter Kardos AppVeyor CI"
  - git clone --single-branch --branch gh-pages git@github.com:petiaccja/LearnToCode.git .
  - xcopy /S /Y C:\projects\LearnToCode\public C:\projects\deploy
  - git add --all
  - git commit -m "Updates generated files"
  - git push