#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}


# branches to build
branches:
  only:
    - master


#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: 
  - Visual Studio 2017

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input
  - choco install hugo

# clone directory
clone_folder: C:\projects\LearnToCode



# this is how to allow failing jobs in the matrix
matrix:
  fast_finish: true
  
environment:
  access_token:
    secure: 44rXJx5ePiHhRQh9LVZDrUXXFNxdydxEhThZiJp4sTP8O/EqN/8s+vWbWT7RyR6i


#---------------------------------#
#       build configuration       #
#---------------------------------#

# to add several platforms to build matrix:
platform:
  - x64

# to add several configurations to build matrix:
configuration:
  - Debug

# We don't want MSBuild
build: off

# Use custom script to build
build_script:
- cmd: |-
    cd /d C:\projects\LearnToCode
    hugo
    

#---------------------------------#
#             deploy              #
#---------------------------------#

on_success:
  - git config --global credential.helper store
  - ps: Add-Content "$HOME\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "kardospeter1994@hotmail.com"
  - git config --global user.name "Peter Kardos AppVeyor CI"
  - mkdir C:\projects\gen
  - mkdir C:\projects\gen\public
  - cd /d C:\projects\LearnToCode
  - xcopy /S public C:\projects\gen\public
  - del /S /Q public
  - git checkout gh-pages
  - xcopy /S C:\projects\gen\public .
  - git add --all
  - git commit -m "Updates generated files"
  - git push
  - git checkout master

